services:
  db:
    image: postgres:16-alpine
    container_name: fuzzer-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fuzzerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/dat

volumes:
  pgdata: