spring.application.name=API-Fuzzer
spring.datasource.url=jdbc:postgresql://localhost:5432/fuzzerdb
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
